# Generated by Django 4.2.25 on 2025-10-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_driverprofile_is_available_driverprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='dropoff_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='dropoff_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
