"""add payments table

Revision ID: 53fdc4a1ff89
Revises: 6fa7ff3fff1e
Create Date: 2025-09-28 19:02:56.868061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53fdc4a1ff89'
down_revision: Union[str, Sequence[str], None] = '6fa7ff3fff1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
