"""add payments table

Revision ID: 6fa7ff3fff1e
Revises: a0ea554e7dfc
Create Date: 2025-09-28 19:02:30.750353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fa7ff3fff1e'
down_revision: Union[str, Sequence[str], None] = 'a0ea554e7dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rides_driver_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_passenger_id'), table_name='rides')
    op.drop_table('rides')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rides',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('passenger_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pickup_location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dropoff_location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('requested', 'accepted', 'in_progress', 'completed', 'canceled', name='ridestatus'), autoincrement=False, nullable=False),
    sa.Column('fare', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('rides_driver_id_fkey')),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], name=op.f('rides_passenger_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rides_pkey'))
    )
    op.create_index(op.f('ix_rides_passenger_id'), 'rides', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_rides_id'), 'rides', ['id'], unique=False)
    op.create_index(op.f('ix_rides_driver_id'), 'rides', ['driver_id'], unique=False)
    # ### end Alembic commands ###
